repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        additional_dependencies: ["toml"]

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        additional_dependencies: ["toml"]
        args:
          - --config=pyproject.toml

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0 # Use the ref you want to point at
    hooks:
      - id: python-use-type-annotations
      - id: python-check-mock-methods

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.42.1
    hooks:
      - id: commitizen
        additional_dependencies: ["toml"]
        stages: [commit-msg]

  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0 # pick a git hash / tag to point to
    hooks:
      - id: pydocstyle
        additional_dependencies: ["tomli"]
        args:
          - --config=pyproject.toml

  - repo: https://github.com/econchick/interrogate
    rev: 1.5.0
    hooks:
      - id: interrogate
        additional_dependencies: ["toml"]

  - repo: https://github.com/hakancelik96/unimport
    rev: 0.16.0
    hooks:
      - id: unimport
        additional_dependencies: ["toml"]
        args:
          - --config=pyproject.toml
